[package]
name = "gateway"
version = "0.0.1"
authors = ["aesteve <arnaud.esteve@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
pretty_env_logger = "0.4"
serde_json = "1.0.59"
futures = "0.3.8"